version: '3.7'
services:
    
    tp.dba.python:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name:  tp.dba.python
        tty: true
        restart: unless-stopped
        working_dir: /root/tp.dba.python
        volumes:
            - ./:/root/tp.dba.python